name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make Releases
      run: sudo apt-get install gcc-multilib g++-multilib mingw-w64;make github
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: release
        title: L programming language latest stable update
        prerelease: false
        files: |
          artifacts/packages/*
